name: Run Scheduler

on: push

jobs:
  Shcedule:
    name: Scheduler
    runs-on: ubuntu-latest
    steps:
    - name: Check-out Scheduler repository
      uses: actions/checkout@v2
    - name: List directory content
      run: |
        echo Directory content:
        ls -a
        echo
      
    - name: Run Script
      run: python Shift_Scheduler.py
      shell: sh
      
    - name: Run GUI
      run: |
        pip install PySimpleGUI 
        python Scheduler_GUI.py
      shell: sh
