name: Run Scheduler

on: push

jobs:
  Shcedule:
    name: Scheduler
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
    - name: Check pull
      run: |
        echo Directory content:
        ls -a
        echo
      
    - name: Run Script
      run: python Shift_Scheduler.py
      shell: sh
