name: Run Scheduler

on: push

jobs:
  Shcedule:
    name: Scheduler
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
      
    - name: Run Script
      run: python ./Shift-Scheduler.py
      shell: sh
