name: Run Scheduler

on: push

jobs:
  Shcedule:
    name: Scheduler
    runs-on: ubuntu-latest
    steps:
    - name: Check-out Scheduler repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install tabulate
      
    - name: Run Script
      run: python Shift_Scheduler.py
      shell: sh
      
